CREATE TABLE USERROLE (
    ID VARCHAR(255),
    TYPE VARCHAR(255)
    PRIMARY KEY(ID)
)
CREATE TABLE USERS (
    EMAIL VARCHAR(255) NOT NULL,
    ISVERIFIED BIT NOT NULL,
    SIGNINMETHOD VARCHAR(150) NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) ,
    PHONENUMBER VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ROLEID VARCHAR(255) NOT NULL,
    PRIMARY KEY (EMAIL),
    FOREIGN KEY (ROLEID) REFERENCES USERROLE (ID)
)


CREATE TABLE ORDERS (
    ID VARCHAR(255),
    USEREMAIL VARCHAR (255),
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(100),
    TOTAL_PRICE FLOAT,
    ORDER_DATE DATE,
    PAYMENT_STATUS BIT NOT NULL
    PRIMARY KEY (ID),
    FOREIGN KEY (USEREMAIL) REFERENCES USERS(EMAIL) 
)


CREATE TABLE ORDER_STATUS (
    ID VARCHAR(255),
    TYPE VARCHAR(255),
    PRIMARY KEY (ID)
)

CREATE TABLE ORDERDETAIL (
    ID VARCHAR(255),
    ORDERID VARCHAR(255),
    PRODUCTID VARCHAR(255),
    QUANTITY INT,
    TOTAL_PRICE FLOAT,
    STATUS VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (STATUS) REFERENCES ORDER_STATUS (ID)
)

CREATE TABLE CATEGORY (
    ID VARCHAR (255),
    TITLE VARCHAR (255),
    PRIMARY KEY (ID)
)

CREATE TABLE PRODUCT (
    ID VARCHAR (255),
    NAME VARCHAR (255),
    DESCRIPTION VARCHAR(255),
    CATEGORY VARCHAR (255),
    PRICE FLOAT,
    QUANTITY INT,
    LAST_UPDATE DATE 
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(ID)
)